name: Periodic checks

on:
  schedule:
    - cron: '35,55 1,12 * * *'

jobs:
  periodic_healthcheck:
    runs-on: ubuntu-18.04
    steps:
      - name: URL Health Check
        uses: Jtalk/url-health-check-action@v2
        with:
          url: https://vast-springs-05175.herokuapp.com/health
