name: Deployment pipeline

on:
  pull_request:
    branches: [master]
    types: [closed]

jobs:
  simple_deployment_pipeline:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: commit messages
        env:
          COMMIT_MESSAGES: ${{ toJson(github.event.commits.*.message) }}
        run: echo "$COMMIT_MESSAGES"
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: npm install
        run: npm install
      - name: lint
        run: npm run eslint
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - name: e2e tests
        uses: cypress-io/github-action@v2
        with:
          run: | 
            npx cypress cache path
            npm run test:e2e
          start: npm run start-prod
          wait-on: http://localhost:3003
      - name: deploy
        if: "!contains(join(env.COMMIT_MESSAGES), "#skip")"
        uses: akhileshns/heroku-deploy@v3.12.12
        with: 
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: vast-springs-05175
          heroku_email: parkpatrick1@gmail.com
          healthcheck: https://vast-springs-05175.herokuapp.com/health
          checkstring: ok
          procfile: "web: node app.js"
          rollbackonhealthcheckfailed: true
      - name: Bump version and push tag
        if: "!contains(join(env.COMMIT_MESSAGES), "#skip")"
        uses: anothrNick/github-tag-action@1.33.0
        env:
          DEFAULT_BUMP: patch
          DRY_RUN: true
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}